### ISSUE TITLE
Handler::report(Throwable $exception) must be compatible report(Exception $e)

### ISSUE THREAD

**Issue by sundarv85** [utz0r2/lashop#9]
I'm using php 7.2.28 and when I do a composer install, I'm seeing the below error

```
PHP Fatal error:  Declaration of App\Exceptions\Handler::report(Throwable $exception) must be compatible with Illuminate\Foundation\Exceptions\Handler::report(Exception $e) in /user/data/lashop/app/Exceptions/Handler.php on line 9
PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in /user/data/lashop/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
Stack trace:
#0 /user/data/lashop/vendor/laravel/framework/src/Illuminate/Container/Container.php(767): ReflectionClass->__construct('App\\Exceptions\\...')
#1 /user/data/lashop/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\Container\Container->build('App\\Exceptions\\...')
#2 /user/data/lashop/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
#3 /user/data/lashop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\Container\Container->make('App\\Exceptions\\...', Array)
#4 in /user/data/lashop/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

Any suggestions what I'm missing here?

**Comment by igoves** [comment]
Hi

Look at stackoverflow [link](https://stackoverflow.com/questions/50840960/script-php-artisan-packagediscover-handling-the-post-autoload-dump-event-retur)
